name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main   # 👈 triggers deploy when pushing to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout source
        uses: actions/checkout@v3

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'   # 👈 match your Flutter SDK version

      # Build Flutter Web
      - name: Build web
        run: flutter build web --release

      # Deploy to GitHub Pages (main branch)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: main         # 👈 deploy directly to main
          force_orphan: true           # 👈 cleans old history (needed when publishing to same branch)
          cname: rupalama.com.np       # 👈 custom domain auto added
