name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'

      - name: Build web
        run: flutter build web --release

      - name: Deploy to /docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main             # ✅ still main
          folder: build/web        # ✅ source of built files
          target-folder: docs      # ✅ goes into /docs
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
          cname: rupalama.com.np
          nojekyll: true